### ISSUE TITLE
FR: Support TypeScript decorators

### ISSUE THREAD

**Issue by elijaholmos** [ambar/vscode-bundle-size#12]
I have discovered that the extension does not work with Typescript decorators. With a file of the following structure:

```ts
import { UseGuards } from '@nestjs/common';
import { Args, Mutation, Parent, Query, ResolveField, Resolver } from '@nestjs/graphql';

@Resolver('User')
export class UserResolver { ... }
```

the extension provides the following error:

```log
2023-07-25T18:00:29.951Z extension measure:error [SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (4:0)]
```

If possible, it would be nice for this extension to function properly in TypeScript files that contain decorators.

**Comment by ambar** [comment]
https://github.com/evanw/esbuild/issues/104

**Comment by ambar** [comment]
The latest v1.6.1 adds support for experimental decorators, please let me know if you have any problems!
