### ISSUE TITLE
Possible memory leak on mac m1

### ISSUE THREAD

**Issue by cisc0disco** [ambar/vscode-bundle-size#16]
Hi, i've noticed after a while in the system monitor esbuild ran by this extension has 5gb ram and when i have only 8 gb, the computer with this extension starts lagging immensely.

**Comment by GagaPoloJr** [comment]
I also encountered the issue when I changed the import from '../' to an alias path ('@/'). 

When I checked the difference, I assumed the extension flagged any path starting with '@' as a library or package. It will calculate the size even if it is not a library and make the esbuild bigger ( if u have many imports component)

I think try to change from @ to ~

**Comment by ambar** [comment]
@cisc0disco @GagaPoloJr 
In the new v1.8.0 the plugin actively stops the esbuild process after measurement, which ensures that memory is freed up!
