### ISSUE TITLE
Add Color Option to `cautionSize` and `dangerSize`

### ISSUE THREAD

**Issue by ianrohde** [ambar/vscode-bundle-size#2]
It'd be nice to be able customize the text color to match our favorite themes:

```
{
  "bundleSize.cautionSize": {
    "type": "number",
    "default": 50,
    "description": "Size limit in KB, display caution color if exceeded",
    "color": "#aaaaaa"
  },
  "bundleSize.dangerSize": {
    "type": "number",
    "default": 100,
    "description": "Size limit in KB, display danger color if exceeded",
    "color": "#bbbbbb"
  }
}
```

**Comment by ambar** [comment]
@ianrohde Released in v1.4.0 (d3c59714904a5ae332ec620d9862defe73f7a948)

**Comment by ianrohde** [comment]
@ambar thanks for adding this! FYI, I just updated the extension, reloaded VSCode, and I'm not seeing the import size text anywhere.

**Comment by ambar** [comment]
@ianrohde It takes some time for first use (installing esbuild).
