### ISSUE TITLE
Hello, please try to add support for React Native and expo imports if possible!

### ISSUE THREAD

**Issue by KostiantynO** [ambar/vscode-bundle-size#3]
Hello, you have developed a nice extension!
Could you please try to add support for `React Native and expo` imports, if possible?

React Native: [docs](https://reactnative.dev/), [npm](https://www.npmjs.com/package/react-native)
Expo: [docs](https://expo.dev/), [npm](https://www.npmjs.com/package/expo)

![image](https://user-images.githubusercontent.com/61573649/154376619-fde39b91-7e35-4519-9790-90d012722421.png)

**Comment by ambar** [comment]
It seems that the RN is using flow (not valid JS): https://unpkg.com/browse/react-native@0.67.2/index.js#L7

**Comment by ambar** [comment]
@KostiantynO Added basic support for RN in v1.7.0

**Comment by ambar** [comment]
So far so good. RN is a new experience for me.
