### ISSUE TITLE
Is this supported on Windows vs code ? 

### ISSUE THREAD

**Issue by damjan25** [ambar/vscode-bundle-size#4]
Is this mac-only extension ? Or is it suppose to work on windows as well ? 
Does not work at the moment on windows 10
v1.66.2

**Comment by ambar** [comment]
It's only tested on macOS, I will verify the use on Windows when I have some free time.

**Comment by ambar** [comment]
@damjan25 It works fine on Windows, you could check the output channel for the error reason: 
![windows - vscode bundle size](https://user-images.githubusercontent.com/105919/171788170-5c2aa221-44c2-4ea2-89bb-b8f554ec4bc8.png)

The most common error could be related to no **Node.js/npm** being installed, which can be found here: https://nodejs.org/en/
