### ISSUE TITLE
FR: Support Bare Module Specifier Resolution

### ISSUE THREAD

**Issue by elijaholmos** [ambar/vscode-bundle-size#7]
many nodejs projects leverage Bare Module Specifier (https://github.com/jkrems/proposal-pkg-exports) to specify custom package imports/exports in the `package.json`. for example, see [`firebase-admin` sdk](https://github.com/firebase/firebase-admin-node/releases/tag/v10.0.0) or even a smaller package like [`set-interval-async`](https://github.com/ealmansi/set-interval-async#in-nodejs).

the `package.json` for these modules will typically be structured like so:
```json
"exports": {
    ".": {
      "types": "./dist/dynamic/set-interval-async.d.cts",
      "require": "./dist/dynamic/set-interval-async.cjs",
      "import": "./dist/dynamic/set-interval-async.mjs"
    },
    "./dynamic": {
      "types": "./dist/dynamic/set-interval-async.d.cts",
      "require": "./dist/dynamic/set-interval-async.cjs",
      "import": "./dist/dynamic/set-interval-async.mjs"
    },
    "./fixed": {
      "types": "./dist/fixed/set-interval-async.d.cts",
      "require": "./dist/fixed/set-interval-async.cjs",
      "import": "./dist/fixed/set-interval-async.mjs"
    }
  }
  ```
  notice how `./package.json` is not included.

currently, the extension errors when attempting to resolve the bundle size of these modules, with an error like so:
```cmd
2022-10-20T00:57:51.490Z extension exception set-interval-async/fixed [Error: Package subpath './package.json' is not defined by "exports" in c:\<path>\node_modules\set-interval-async\package.json]
```

My feature request is to support the bare module specifier syntax as described above.

**Comment by ambar** [comment]
@elijaholmos Released in v1.5.0, should work now: 
<img width="841" alt="image" src="https://user-images.githubusercontent.com/105919/196951064-952d47bd-a4de-4d19-b41a-be816af4acef.png">

**Comment by elijaholmos** [comment]
thanks for the quick response, @ambar! the extension works much better:
![image](https://user-images.githubusercontent.com/35435704/197002441-1130f2a6-db84-4dd3-9600-54588734d69f.png)


![image](https://user-images.githubusercontent.com/35435704/197002663-3693ed66-b54f-425c-91d6-c49c11697dfa.png)

only problem I see now is in the above screenshot with `firebase-admin/database`. here's the extension output for my file:
![image](https://user-images.githubusercontent.com/35435704/197002903-206e3350-0d5e-43aa-9c90-e775a136d50e.png)

not sure if this is a problem with my machine, the `firebase-admin` package, or something else 😅  I don't mind one package not working, though- everything else has worked greatly!

**Comment by ambar** [comment]
@elijaholmos Thanks for the feedback, I'll look at that question when I have time.

**Comment by ambar** [comment]
It seems `firebase-admin` is a package that only supports node, not browser (which is the default of the Bundle Size plugin), at least in current version of esbuild (maybe a compatibility issue of `exports` field).

```bash

# ok
echo "import { getDatabase } from 'firebase-admin/database'" | yarn esbuild --bundle --platform=node --minify > bundle.js

# fail
echo "import { getDatabase } from 'firebase-admin/database'" | yarn esbuild --bundle --platform=browser --minify > bundle.js


✘ [ERROR] Could not resolve "@firebase/database-compat/standalone"

    node_modules/firebase-admin/lib/database/index.js:20:29:
      20 │ const standalone_1 = require("@firebase/database-compat/standalone");
         ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./standalone" is not currently exported by package "@firebase/database-compat":

    node_modules/@firebase/database-compat/package.json:16:13:
      16 │   "exports": {
         ╵              ^

  None of the conditions provided ("types", "node") match any of the currently active conditions
  ("browser", "default", "require"):

    node_modules/@firebase/database-compat/package.json:27:20:
      27 │     "./standalone": {
```

**Comment by elijaholmos** [comment]
I see, so it looks like it's an issue on the package level. thank you for looking into it!
