### ISSUE TITLE
Esbuild Memory Hog  

### ISSUE THREAD

**Issue by a-tarek** [ambar/vscode-bundle-size#8]
Not sure where the problem would be 
Developing on a react app with typescript and lazy imports 
Memory starts leaking after opening multiple files / saves / sort imports / etc .. 
It starts out incremental on each save and then it start eating memory by itself as if it is stuck in a loop

<img width="765" alt="image" src="https://user-images.githubusercontent.com/23399734/200313793-200e0309-0160-447e-b3ff-74d64bb00c48.png">

**Comment by ambar** [comment]
Sorry for the late reply, since I can't reproduce the problem, my suggestion is to reinstall/upgrade to the latest version (which will trigger an update to esbuild, maybe it solves the problem).

**Comment by ambar** [comment]
The latest v1.6.0 has changed to a lazy async generator API, and now parallel bundling are limited to one, which should result in better performance. If you still have problems, please reopen it.

**Comment by ambar** [comment]
#19
